Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -97,9 +97,12 @@ jobs:
       - name: Run Python Tests
         if: env.LANGUAGE == 'Python'
         run: |
-          set -e
           echo "Running Python Test Cases..."
-          python3 tests/test.py | tee test_results.log
+          python3 tests/test.py
+          if [ $? -ne 0 ]; then
+            echo "Test failed, exiting with status 1."
+            exit 1
+          fi
 
 
       - name: Upload Test Results
